"""Add status field to campaigns

Revision ID: bd07c522f699
Revises: ad21a6b25f74
Create Date: 2025-02-07 15:56:43.951143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd07c522f699'
down_revision: Union[str, None] = 'ad21a6b25f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'status')
    # ### end Alembic commands ###
